package com.example.test2

enum class ModbusCommand(val address: Int) {
    POWER(1),
    LOCK(2),
    BUZZER(3),
    DIRECTION(4),
    MODE(5),
    HANDLING(6),
    EMERGENCY_STOP(7),
    COUNT_PALLET(8),
    PICK_PALLET(9),
    STACK_A(10),
    TAKE_PALLET(11),
    STACK_B(12),
    FORWARD(13),
    REVERSE(14),
    UP(15),
    DOWN(16),
    BATTERY(17),
    PICK_PALLETS(18),
    TAKE_PALLETS(19),
    LOCATION(20),
    OPERATION_STATUS(21),

    START_X(25),
    START_Y(26),
    START_Z(27),
    END_X(28),
    END_Y(29),
    END_Z(30),
    ACTUAL_X(31),
    ACTUAL_Y(32),
    ACTUAL_Z(33),
    FUNCTION_MODE(34)
}